// Code generated by protoc-gen-go. DO NOT EDIT.
// source: obsolete.proto

package dialog

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObsoleteTypingType int32

const (
	ObsoleteTypingType_OBSOLETE_TYPINGTYPE_UNKNOWN ObsoleteTypingType = 0
	ObsoleteTypingType_OBSOLETE_TYPINGTYPE_TEXT    ObsoleteTypingType = 1
)

var ObsoleteTypingType_name = map[int32]string{
	0: "OBSOLETE_TYPINGTYPE_UNKNOWN",
	1: "OBSOLETE_TYPINGTYPE_TEXT",
}

var ObsoleteTypingType_value = map[string]int32{
	"OBSOLETE_TYPINGTYPE_UNKNOWN": 0,
	"OBSOLETE_TYPINGTYPE_TEXT":    1,
}

func (x ObsoleteTypingType) String() string {
	return proto.EnumName(ObsoleteTypingType_name, int32(x))
}

func (ObsoleteTypingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{0}
}

type ObsoletePeer_ObsoletePeerType int32

const (
	ObsoletePeer_OBSOLETE_PEERTYPE_UNKNOWN ObsoletePeer_ObsoletePeerType = 0
	ObsoletePeer_OBSOLETE_PEERTYPE_PRIVATE ObsoletePeer_ObsoletePeerType = 1
	ObsoletePeer_OBSOLETE_PEERTYPE_GROUP   ObsoletePeer_ObsoletePeerType = 2
	//PEERTYPE_ENCRYPTED_PRIVATE = 3;
	ObsoletePeer_OBSOLETE_PEERTYPE_SIP ObsoletePeer_ObsoletePeerType = 4
)

var ObsoletePeer_ObsoletePeerType_name = map[int32]string{
	0: "OBSOLETE_PEERTYPE_UNKNOWN",
	1: "OBSOLETE_PEERTYPE_PRIVATE",
	2: "OBSOLETE_PEERTYPE_GROUP",
	4: "OBSOLETE_PEERTYPE_SIP",
}

var ObsoletePeer_ObsoletePeerType_value = map[string]int32{
	"OBSOLETE_PEERTYPE_UNKNOWN": 0,
	"OBSOLETE_PEERTYPE_PRIVATE": 1,
	"OBSOLETE_PEERTYPE_GROUP":   2,
	"OBSOLETE_PEERTYPE_SIP":     4,
}

func (x ObsoletePeer_ObsoletePeerType) String() string {
	return proto.EnumName(ObsoletePeer_ObsoletePeerType_name, int32(x))
}

func (ObsoletePeer_ObsoletePeerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{0, 0}
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason int32

const (
	ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_OBSOLETE_DISPOSAL_REASON_UNKNOWN        ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason = 0
	ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_OBSOLETE_DISPOSAL_REASON_REJECTED       ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason = 1
	ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_OBSOLETE_DISPOSAL_REASON_BUSY           ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason = 2
	ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_OBSOLETE_DISPOSAL_REASON_ENDED          ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason = 3
	ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_OBSOLETE_DISPOSAL_REASON_ANSWER_TIMEOUT ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason = 4
)

var ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason_name = map[int32]string{
	0: "OBSOLETE_DISPOSAL_REASON_UNKNOWN",
	1: "OBSOLETE_DISPOSAL_REASON_REJECTED",
	2: "OBSOLETE_DISPOSAL_REASON_BUSY",
	3: "OBSOLETE_DISPOSAL_REASON_ENDED",
	4: "OBSOLETE_DISPOSAL_REASON_ANSWER_TIMEOUT",
}

var ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason_value = map[string]int32{
	"OBSOLETE_DISPOSAL_REASON_UNKNOWN":        0,
	"OBSOLETE_DISPOSAL_REASON_REJECTED":       1,
	"OBSOLETE_DISPOSAL_REASON_BUSY":           2,
	"OBSOLETE_DISPOSAL_REASON_ENDED":          3,
	"OBSOLETE_DISPOSAL_REASON_ANSWER_TIMEOUT": 4,
}

func (x ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason) String() string {
	return proto.EnumName(ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason_name, int32(x))
}

func (ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 9, 0}
}

type ObsoletePeer struct {
	Type                 ObsoletePeer_ObsoletePeerType `protobuf:"varint,1,opt,name=type,proto3,enum=dialog.ObsoletePeer_ObsoletePeerType" json:"type,omitempty"`
	Id                   int32                         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	StrId                *wrappers.StringValue         `protobuf:"bytes,3,opt,name=strId,proto3" json:"strId,omitempty"`
	AccessHash           int64                         `protobuf:"varint,4,opt,name=access_hash,json=accessHash,proto3" json:"access_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ObsoletePeer) Reset()         { *m = ObsoletePeer{} }
func (m *ObsoletePeer) String() string { return proto.CompactTextString(m) }
func (*ObsoletePeer) ProtoMessage()    {}
func (*ObsoletePeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{0}
}

func (m *ObsoletePeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoletePeer.Unmarshal(m, b)
}
func (m *ObsoletePeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoletePeer.Marshal(b, m, deterministic)
}
func (m *ObsoletePeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoletePeer.Merge(m, src)
}
func (m *ObsoletePeer) XXX_Size() int {
	return xxx_messageInfo_ObsoletePeer.Size(m)
}
func (m *ObsoletePeer) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoletePeer.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoletePeer proto.InternalMessageInfo

func (m *ObsoletePeer) GetType() ObsoletePeer_ObsoletePeerType {
	if m != nil {
		return m.Type
	}
	return ObsoletePeer_OBSOLETE_PEERTYPE_UNKNOWN
}

func (m *ObsoletePeer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ObsoletePeer) GetStrId() *wrappers.StringValue {
	if m != nil {
		return m.StrId
	}
	return nil
}

func (m *ObsoletePeer) GetAccessHash() int64 {
	if m != nil {
		return m.AccessHash
	}
	return 0
}

type ObsoleteOutPeer struct {
	Peer                 *ObsoletePeer `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	AccessHash           int64         `protobuf:"varint,2,opt,name=accessHash,proto3" json:"accessHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObsoleteOutPeer) Reset()         { *m = ObsoleteOutPeer{} }
func (m *ObsoleteOutPeer) String() string { return proto.CompactTextString(m) }
func (*ObsoleteOutPeer) ProtoMessage()    {}
func (*ObsoleteOutPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{1}
}

func (m *ObsoleteOutPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteOutPeer.Unmarshal(m, b)
}
func (m *ObsoleteOutPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteOutPeer.Marshal(b, m, deterministic)
}
func (m *ObsoleteOutPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteOutPeer.Merge(m, src)
}
func (m *ObsoleteOutPeer) XXX_Size() int {
	return xxx_messageInfo_ObsoleteOutPeer.Size(m)
}
func (m *ObsoleteOutPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteOutPeer.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteOutPeer proto.InternalMessageInfo

func (m *ObsoleteOutPeer) GetPeer() *ObsoletePeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *ObsoleteOutPeer) GetAccessHash() int64 {
	if m != nil {
		return m.AccessHash
	}
	return 0
}

type ObsoletePeersList struct {
	Peers                []*ObsoletePeer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObsoletePeersList) Reset()         { *m = ObsoletePeersList{} }
func (m *ObsoletePeersList) String() string { return proto.CompactTextString(m) }
func (*ObsoletePeersList) ProtoMessage()    {}
func (*ObsoletePeersList) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{2}
}

func (m *ObsoletePeersList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoletePeersList.Unmarshal(m, b)
}
func (m *ObsoletePeersList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoletePeersList.Marshal(b, m, deterministic)
}
func (m *ObsoletePeersList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoletePeersList.Merge(m, src)
}
func (m *ObsoletePeersList) XXX_Size() int {
	return xxx_messageInfo_ObsoletePeersList.Size(m)
}
func (m *ObsoletePeersList) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoletePeersList.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoletePeersList proto.InternalMessageInfo

func (m *ObsoletePeersList) GetPeers() []*ObsoletePeer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type ObsoleteGetDifferenceCommand struct {
	Seq                  *wrappers.Int32Value `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	State                []byte               `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ConfigHash           int64                `protobuf:"varint,3,opt,name=configHash,proto3" json:"configHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ObsoleteGetDifferenceCommand) Reset()         { *m = ObsoleteGetDifferenceCommand{} }
func (m *ObsoleteGetDifferenceCommand) String() string { return proto.CompactTextString(m) }
func (*ObsoleteGetDifferenceCommand) ProtoMessage()    {}
func (*ObsoleteGetDifferenceCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{3}
}

func (m *ObsoleteGetDifferenceCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteGetDifferenceCommand.Unmarshal(m, b)
}
func (m *ObsoleteGetDifferenceCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteGetDifferenceCommand.Marshal(b, m, deterministic)
}
func (m *ObsoleteGetDifferenceCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteGetDifferenceCommand.Merge(m, src)
}
func (m *ObsoleteGetDifferenceCommand) XXX_Size() int {
	return xxx_messageInfo_ObsoleteGetDifferenceCommand.Size(m)
}
func (m *ObsoleteGetDifferenceCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteGetDifferenceCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteGetDifferenceCommand proto.InternalMessageInfo

func (m *ObsoleteGetDifferenceCommand) GetSeq() *wrappers.Int32Value {
	if m != nil {
		return m.Seq
	}
	return nil
}

func (m *ObsoleteGetDifferenceCommand) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ObsoleteGetDifferenceCommand) GetConfigHash() int64 {
	if m != nil {
		return m.ConfigHash
	}
	return 0
}

type ObsoleteSeqUpdateBox struct {
	Seq   int32  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	State []byte `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Updatebox:
	//	*ObsoleteSeqUpdateBox_ObsoleteUpdate
	Updatebox            isObsoleteSeqUpdateBox_Updatebox `protobuf_oneof:"updatebox"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ObsoleteSeqUpdateBox) Reset()         { *m = ObsoleteSeqUpdateBox{} }
func (m *ObsoleteSeqUpdateBox) String() string { return proto.CompactTextString(m) }
func (*ObsoleteSeqUpdateBox) ProtoMessage()    {}
func (*ObsoleteSeqUpdateBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{4}
}

func (m *ObsoleteSeqUpdateBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteSeqUpdateBox.Unmarshal(m, b)
}
func (m *ObsoleteSeqUpdateBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteSeqUpdateBox.Marshal(b, m, deterministic)
}
func (m *ObsoleteSeqUpdateBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteSeqUpdateBox.Merge(m, src)
}
func (m *ObsoleteSeqUpdateBox) XXX_Size() int {
	return xxx_messageInfo_ObsoleteSeqUpdateBox.Size(m)
}
func (m *ObsoleteSeqUpdateBox) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteSeqUpdateBox.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteSeqUpdateBox proto.InternalMessageInfo

func (m *ObsoleteSeqUpdateBox) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ObsoleteSeqUpdateBox) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

type isObsoleteSeqUpdateBox_Updatebox interface {
	isObsoleteSeqUpdateBox_Updatebox()
}

type ObsoleteSeqUpdateBox_ObsoleteUpdate struct {
	ObsoleteUpdate *wrappers.BytesValue `protobuf:"bytes,3,opt,name=obsoleteUpdate,proto3,oneof"`
}

func (*ObsoleteSeqUpdateBox_ObsoleteUpdate) isObsoleteSeqUpdateBox_Updatebox() {}

func (m *ObsoleteSeqUpdateBox) GetUpdatebox() isObsoleteSeqUpdateBox_Updatebox {
	if m != nil {
		return m.Updatebox
	}
	return nil
}

func (m *ObsoleteSeqUpdateBox) GetObsoleteUpdate() *wrappers.BytesValue {
	if x, ok := m.GetUpdatebox().(*ObsoleteSeqUpdateBox_ObsoleteUpdate); ok {
		return x.ObsoleteUpdate
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObsoleteSeqUpdateBox) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObsoleteSeqUpdateBox_ObsoleteUpdate)(nil),
	}
}

type ObsoleteWeakUpdateBox struct {
	Date int64 `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	// Types that are valid to be assigned to Updatebox:
	//	*ObsoleteWeakUpdateBox_Typing
	//	*ObsoleteWeakUpdateBox_UserLastSeen
	//	*ObsoleteWeakUpdateBox_GroupOnline
	//	*ObsoleteWeakUpdateBox_BusMessage
	//	*ObsoleteWeakUpdateBox_BusDeviceConnected
	//	*ObsoleteWeakUpdateBox_BusDeviceDisconnected
	//	*ObsoleteWeakUpdateBox_BusDisposed
	//	*ObsoleteWeakUpdateBox_ForceReload
	//	*ObsoleteWeakUpdateBox_IncomingCall
	//	*ObsoleteWeakUpdateBox_CallHandled
	//	*ObsoleteWeakUpdateBox_CallDisposed
	Updatebox            isObsoleteWeakUpdateBox_Updatebox `protobuf_oneof:"updatebox"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ObsoleteWeakUpdateBox) Reset()         { *m = ObsoleteWeakUpdateBox{} }
func (m *ObsoleteWeakUpdateBox) String() string { return proto.CompactTextString(m) }
func (*ObsoleteWeakUpdateBox) ProtoMessage()    {}
func (*ObsoleteWeakUpdateBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5}
}

func (m *ObsoleteWeakUpdateBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox.Size(m)
}
func (m *ObsoleteWeakUpdateBox) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type isObsoleteWeakUpdateBox_Updatebox interface {
	isObsoleteWeakUpdateBox_Updatebox()
}

type ObsoleteWeakUpdateBox_Typing struct {
	Typing *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping `protobuf:"bytes,2,opt,name=typing,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_UserLastSeen struct {
	UserLastSeen *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen `protobuf:"bytes,3,opt,name=userLastSeen,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_GroupOnline struct {
	GroupOnline *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline `protobuf:"bytes,4,opt,name=groupOnline,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_BusMessage struct {
	BusMessage *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage `protobuf:"bytes,5,opt,name=busMessage,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_BusDeviceConnected struct {
	BusDeviceConnected *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected `protobuf:"bytes,6,opt,name=busDeviceConnected,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_BusDeviceDisconnected struct {
	BusDeviceDisconnected *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected `protobuf:"bytes,7,opt,name=busDeviceDisconnected,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_BusDisposed struct {
	BusDisposed *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed `protobuf:"bytes,8,opt,name=busDisposed,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_ForceReload struct {
	ForceReload *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState `protobuf:"bytes,9,opt,name=forceReload,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_IncomingCall struct {
	IncomingCall *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall `protobuf:"bytes,10,opt,name=incomingCall,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_CallHandled struct {
	CallHandled *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled `protobuf:"bytes,11,opt,name=callHandled,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_CallDisposed struct {
	CallDisposed *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed `protobuf:"bytes,12,opt,name=callDisposed,proto3,oneof"`
}

func (*ObsoleteWeakUpdateBox_Typing) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_UserLastSeen) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_GroupOnline) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_BusMessage) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_BusDeviceConnected) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_BusDeviceDisconnected) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_BusDisposed) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_ForceReload) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_IncomingCall) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_CallHandled) isObsoleteWeakUpdateBox_Updatebox() {}

func (*ObsoleteWeakUpdateBox_CallDisposed) isObsoleteWeakUpdateBox_Updatebox() {}

func (m *ObsoleteWeakUpdateBox) GetUpdatebox() isObsoleteWeakUpdateBox_Updatebox {
	if m != nil {
		return m.Updatebox
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetTyping() *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_Typing); ok {
		return x.Typing
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetUserLastSeen() *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_UserLastSeen); ok {
		return x.UserLastSeen
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetGroupOnline() *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_GroupOnline); ok {
		return x.GroupOnline
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetBusMessage() *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_BusMessage); ok {
		return x.BusMessage
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetBusDeviceConnected() *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_BusDeviceConnected); ok {
		return x.BusDeviceConnected
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetBusDeviceDisconnected() *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_BusDeviceDisconnected); ok {
		return x.BusDeviceDisconnected
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetBusDisposed() *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_BusDisposed); ok {
		return x.BusDisposed
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetForceReload() *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_ForceReload); ok {
		return x.ForceReload
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetIncomingCall() *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_IncomingCall); ok {
		return x.IncomingCall
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetCallHandled() *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_CallHandled); ok {
		return x.CallHandled
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox) GetCallDisposed() *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed {
	if x, ok := m.GetUpdatebox().(*ObsoleteWeakUpdateBox_CallDisposed); ok {
		return x.CallDisposed
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObsoleteWeakUpdateBox) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObsoleteWeakUpdateBox_Typing)(nil),
		(*ObsoleteWeakUpdateBox_UserLastSeen)(nil),
		(*ObsoleteWeakUpdateBox_GroupOnline)(nil),
		(*ObsoleteWeakUpdateBox_BusMessage)(nil),
		(*ObsoleteWeakUpdateBox_BusDeviceConnected)(nil),
		(*ObsoleteWeakUpdateBox_BusDeviceDisconnected)(nil),
		(*ObsoleteWeakUpdateBox_BusDisposed)(nil),
		(*ObsoleteWeakUpdateBox_ForceReload)(nil),
		(*ObsoleteWeakUpdateBox_IncomingCall)(nil),
		(*ObsoleteWeakUpdateBox_CallHandled)(nil),
		(*ObsoleteWeakUpdateBox_CallDisposed)(nil),
	}
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateTyping struct {
	Peer                 *ObsoletePeer      `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	UserId               int32              `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 ObsoleteTypingType `protobuf:"varint,3,opt,name=type,proto3,enum=dialog.ObsoleteTypingType" json:"type,omitempty"`
	IsTyping             bool               `protobuf:"varint,4,opt,name=isTyping,proto3" json:"isTyping,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateTyping{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 0}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateTyping.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateTyping.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateTyping.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateTyping.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateTyping.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateTyping proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) GetPeer() *ObsoletePeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) GetType() ObsoleteTypingType {
	if m != nil {
		return m.Type
	}
	return ObsoleteTypingType_OBSOLETE_TYPINGTYPE_UNKNOWN
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateTyping) GetIsTyping() bool {
	if m != nil {
		return m.IsTyping
	}
	return false
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EpochMillis          int64    `protobuf:"varint,2,opt,name=epochMillis,proto3" json:"epochMillis,omitempty"`
	DeviceType           int32    `protobuf:"varint,3,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	DeviceCategory       string   `protobuf:"bytes,4,opt,name=deviceCategory,proto3" json:"deviceCategory,omitempty"`
	IsOnline             bool     `protobuf:"varint,5,opt,name=isOnline,proto3" json:"isOnline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 1}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) GetEpochMillis() int64 {
	if m != nil {
		return m.EpochMillis
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) GetDeviceCategory() string {
	if m != nil {
		return m.DeviceCategory
	}
	return ""
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline struct {
	GroupId              int32    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 2}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage struct {
	BusId                string               `protobuf:"bytes,1,opt,name=busId,proto3" json:"busId,omitempty"`
	SenderId             *wrappers.Int32Value `protobuf:"bytes,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	SenderDeviceId       *wrappers.Int64Value `protobuf:"bytes,3,opt,name=senderDeviceId,proto3" json:"senderDeviceId,omitempty"`
	Message              []byte               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 3}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) GetBusId() string {
	if m != nil {
		return m.BusId
	}
	return ""
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) GetSenderId() *wrappers.Int32Value {
	if m != nil {
		return m.SenderId
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) GetSenderDeviceId() *wrappers.Int64Value {
	if m != nil {
		return m.SenderDeviceId
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected struct {
	BusId                string               `protobuf:"bytes,1,opt,name=busId,proto3" json:"busId,omitempty"`
	UserId               *wrappers.Int32Value `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId             int64                `protobuf:"varint,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 4}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) GetBusId() string {
	if m != nil {
		return m.BusId
	}
	return ""
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) GetUserId() *wrappers.Int32Value {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected struct {
	BusId                string               `protobuf:"bytes,1,opt,name=busId,proto3" json:"busId,omitempty"`
	UserId               *wrappers.Int32Value `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId             int64                `protobuf:"varint,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 5}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) GetBusId() string {
	if m != nil {
		return m.BusId
	}
	return ""
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) GetUserId() *wrappers.Int32Value {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed struct {
	BusId                string   `protobuf:"bytes,1,opt,name=busId,proto3" json:"busId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 6}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed) GetBusId() string {
	if m != nil {
		return m.BusId
	}
	return ""
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall struct {
	CallId               int64                 `protobuf:"varint,1,opt,name=callId,proto3" json:"callId,omitempty"`
	BusId                string                `protobuf:"bytes,2,opt,name=busId,proto3" json:"busId,omitempty"`
	Peer                 *ObsoletePeer         `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	DisplayName          *wrappers.StringValue `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	AttemptIndex         *wrappers.Int32Value  `protobuf:"bytes,5,opt,name=attemptIndex,proto3" json:"attemptIndex,omitempty"`
	OutPeer              *ObsoleteOutPeer      `protobuf:"bytes,6,opt,name=outPeer,proto3" json:"outPeer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 7}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) GetCallId() int64 {
	if m != nil {
		return m.CallId
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) GetBusId() string {
	if m != nil {
		return m.BusId
	}
	return ""
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) GetPeer() *ObsoletePeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) GetDisplayName() *wrappers.StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) GetAttemptIndex() *wrappers.Int32Value {
	if m != nil {
		return m.AttemptIndex
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall) GetOutPeer() *ObsoleteOutPeer {
	if m != nil {
		return m.OutPeer
	}
	return nil
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled struct {
	CallId               int64                `protobuf:"varint,1,opt,name=callId,proto3" json:"callId,omitempty"`
	AttemptIndex         *wrappers.Int32Value `protobuf:"bytes,2,opt,name=attemptIndex,proto3" json:"attemptIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 8}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) GetCallId() int64 {
	if m != nil {
		return m.CallId
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled) GetAttemptIndex() *wrappers.Int32Value {
	if m != nil {
		return m.AttemptIndex
	}
	return nil
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed struct {
	CallId               int64                                                                   `protobuf:"varint,1,opt,name=callId,proto3" json:"callId,omitempty"`
	AttemptIndex         *wrappers.Int32Value                                                    `protobuf:"bytes,2,opt,name=attemptIndex,proto3" json:"attemptIndex,omitempty"`
	Reason               ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason `protobuf:"varint,3,opt,name=reason,proto3,enum=dialog.ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                `json:"-"`
	XXX_unrecognized     []byte                                                                  `json:"-"`
	XXX_sizecache        int32                                                                   `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 9}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) GetCallId() int64 {
	if m != nil {
		return m.CallId
	}
	return 0
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) GetAttemptIndex() *wrappers.Int32Value {
	if m != nil {
		return m.AttemptIndex
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed) GetReason() ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason {
	if m != nil {
		return m.Reason
	}
	return ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_OBSOLETE_DISPOSAL_REASON_UNKNOWN
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState struct {
	Fields               []*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                         `json:"-"`
	XXX_unrecognized     []byte                                                                           `json:"-"`
	XXX_sizecache        int32                                                                            `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 10}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState) GetFields() []*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField struct {
	// Types that are valid to be assigned to Field:
	//	*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadDialogs
	//	*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadContacts
	//	*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadHistory
	Field                isObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_Field `protobuf_oneof:"field"`
	XXX_NoUnkeyedLiteral struct{}                                                                              `json:"-"`
	XXX_unrecognized     []byte                                                                                `json:"-"`
	XXX_sizecache        int32                                                                                 `json:"-"`
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) Reset() {
	*m = ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField{}
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) ProtoMessage() {}
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{5, 10, 0}
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField.Merge(m, src)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField.Size(m)
}
func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField proto.InternalMessageInfo

type isObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_Field interface {
	isObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_Field()
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadDialogs struct {
	ReloadDialogs *empty.Empty `protobuf:"bytes,1,opt,name=reloadDialogs,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadContacts struct {
	ReloadContacts *empty.Empty `protobuf:"bytes,2,opt,name=reloadContacts,proto3,oneof"`
}

type ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadHistory struct {
	ReloadHistory *ObsoletePeersList `protobuf:"bytes,3,opt,name=reloadHistory,proto3,oneof"`
}

func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadDialogs) isObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_Field() {
}

func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadContacts) isObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_Field() {
}

func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadHistory) isObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_Field() {
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) GetField() isObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) GetReloadDialogs() *empty.Empty {
	if x, ok := m.GetField().(*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadDialogs); ok {
		return x.ReloadDialogs
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) GetReloadContacts() *empty.Empty {
	if x, ok := m.GetField().(*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadContacts); ok {
		return x.ReloadContacts
	}
	return nil
}

func (m *ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) GetReloadHistory() *ObsoletePeersList {
	if x, ok := m.GetField().(*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadHistory); ok {
		return x.ReloadHistory
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadDialogs)(nil),
		(*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadContacts)(nil),
		(*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField_ReloadHistory)(nil),
	}
}

type ObsoleteServiceUpdate struct {
	// Types that are valid to be assigned to Update:
	//	*ObsoleteServiceUpdate_ObsoleteUpdate
	Update               isObsoleteServiceUpdate_Update `protobuf_oneof:"update"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ObsoleteServiceUpdate) Reset()         { *m = ObsoleteServiceUpdate{} }
func (m *ObsoleteServiceUpdate) String() string { return proto.CompactTextString(m) }
func (*ObsoleteServiceUpdate) ProtoMessage()    {}
func (*ObsoleteServiceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{6}
}

func (m *ObsoleteServiceUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteServiceUpdate.Unmarshal(m, b)
}
func (m *ObsoleteServiceUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteServiceUpdate.Marshal(b, m, deterministic)
}
func (m *ObsoleteServiceUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteServiceUpdate.Merge(m, src)
}
func (m *ObsoleteServiceUpdate) XXX_Size() int {
	return xxx_messageInfo_ObsoleteServiceUpdate.Size(m)
}
func (m *ObsoleteServiceUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteServiceUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteServiceUpdate proto.InternalMessageInfo

type isObsoleteServiceUpdate_Update interface {
	isObsoleteServiceUpdate_Update()
}

type ObsoleteServiceUpdate_ObsoleteUpdate struct {
	ObsoleteUpdate *wrappers.BytesValue `protobuf:"bytes,1,opt,name=obsoleteUpdate,proto3,oneof"`
}

func (*ObsoleteServiceUpdate_ObsoleteUpdate) isObsoleteServiceUpdate_Update() {}

func (m *ObsoleteServiceUpdate) GetUpdate() isObsoleteServiceUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *ObsoleteServiceUpdate) GetObsoleteUpdate() *wrappers.BytesValue {
	if x, ok := m.GetUpdate().(*ObsoleteServiceUpdate_ObsoleteUpdate); ok {
		return x.ObsoleteUpdate
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObsoleteServiceUpdate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObsoleteServiceUpdate_ObsoleteUpdate)(nil),
	}
}

type ObsoleteWeakUpdateCommand struct {
	// Types that are valid to be assigned to Command:
	//	*ObsoleteWeakUpdateCommand_SubscribeToOnlines
	//	*ObsoleteWeakUpdateCommand_UnsubscribeFromOnlines
	//	*ObsoleteWeakUpdateCommand_DropOnlineSubscriptions
	//	*ObsoleteWeakUpdateCommand_MyTyping
	//	*ObsoleteWeakUpdateCommand_SubscribeToTypings
	//	*ObsoleteWeakUpdateCommand_UnsubscribeFromTypings
	//	*ObsoleteWeakUpdateCommand_DropTypingSubscriptions
	//	*ObsoleteWeakUpdateCommand_SubscribeToEventBusUpdates
	//	*ObsoleteWeakUpdateCommand_MyOnline
	Command              isObsoleteWeakUpdateCommand_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ObsoleteWeakUpdateCommand) Reset()         { *m = ObsoleteWeakUpdateCommand{} }
func (m *ObsoleteWeakUpdateCommand) String() string { return proto.CompactTextString(m) }
func (*ObsoleteWeakUpdateCommand) ProtoMessage()    {}
func (*ObsoleteWeakUpdateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{7}
}

func (m *ObsoleteWeakUpdateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateCommand.Merge(m, src)
}
func (m *ObsoleteWeakUpdateCommand) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand.Size(m)
}
func (m *ObsoleteWeakUpdateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateCommand proto.InternalMessageInfo

type isObsoleteWeakUpdateCommand_Command interface {
	isObsoleteWeakUpdateCommand_Command()
}

type ObsoleteWeakUpdateCommand_SubscribeToOnlines struct {
	SubscribeToOnlines *ObsoletePeersList `protobuf:"bytes,1,opt,name=subscribeToOnlines,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_UnsubscribeFromOnlines struct {
	UnsubscribeFromOnlines *ObsoletePeersList `protobuf:"bytes,2,opt,name=unsubscribeFromOnlines,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_DropOnlineSubscriptions struct {
	DropOnlineSubscriptions *empty.Empty `protobuf:"bytes,3,opt,name=dropOnlineSubscriptions,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_MyTyping struct {
	MyTyping *ObsoleteWeakUpdateCommand_ObsoleteMyTyping `protobuf:"bytes,7,opt,name=myTyping,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_SubscribeToTypings struct {
	SubscribeToTypings *ObsoletePeersList `protobuf:"bytes,8,opt,name=subscribeToTypings,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_UnsubscribeFromTypings struct {
	UnsubscribeFromTypings *ObsoletePeersList `protobuf:"bytes,9,opt,name=unsubscribeFromTypings,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_DropTypingSubscriptions struct {
	DropTypingSubscriptions *empty.Empty `protobuf:"bytes,10,opt,name=dropTypingSubscriptions,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_SubscribeToEventBusUpdates struct {
	SubscribeToEventBusUpdates *empty.Empty `protobuf:"bytes,11,opt,name=subscribeToEventBusUpdates,proto3,oneof"`
}

type ObsoleteWeakUpdateCommand_MyOnline struct {
	MyOnline *ObsoleteWeakUpdateCommand_ObsoleteMyOnline `protobuf:"bytes,12,opt,name=myOnline,proto3,oneof"`
}

func (*ObsoleteWeakUpdateCommand_SubscribeToOnlines) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_UnsubscribeFromOnlines) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_DropOnlineSubscriptions) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_MyTyping) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_SubscribeToTypings) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_UnsubscribeFromTypings) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_DropTypingSubscriptions) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_SubscribeToEventBusUpdates) isObsoleteWeakUpdateCommand_Command() {}

func (*ObsoleteWeakUpdateCommand_MyOnline) isObsoleteWeakUpdateCommand_Command() {}

func (m *ObsoleteWeakUpdateCommand) GetCommand() isObsoleteWeakUpdateCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetSubscribeToOnlines() *ObsoletePeersList {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_SubscribeToOnlines); ok {
		return x.SubscribeToOnlines
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetUnsubscribeFromOnlines() *ObsoletePeersList {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_UnsubscribeFromOnlines); ok {
		return x.UnsubscribeFromOnlines
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetDropOnlineSubscriptions() *empty.Empty {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_DropOnlineSubscriptions); ok {
		return x.DropOnlineSubscriptions
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetMyTyping() *ObsoleteWeakUpdateCommand_ObsoleteMyTyping {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_MyTyping); ok {
		return x.MyTyping
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetSubscribeToTypings() *ObsoletePeersList {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_SubscribeToTypings); ok {
		return x.SubscribeToTypings
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetUnsubscribeFromTypings() *ObsoletePeersList {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_UnsubscribeFromTypings); ok {
		return x.UnsubscribeFromTypings
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetDropTypingSubscriptions() *empty.Empty {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_DropTypingSubscriptions); ok {
		return x.DropTypingSubscriptions
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetSubscribeToEventBusUpdates() *empty.Empty {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_SubscribeToEventBusUpdates); ok {
		return x.SubscribeToEventBusUpdates
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand) GetMyOnline() *ObsoleteWeakUpdateCommand_ObsoleteMyOnline {
	if x, ok := m.GetCommand().(*ObsoleteWeakUpdateCommand_MyOnline); ok {
		return x.MyOnline
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObsoleteWeakUpdateCommand) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObsoleteWeakUpdateCommand_SubscribeToOnlines)(nil),
		(*ObsoleteWeakUpdateCommand_UnsubscribeFromOnlines)(nil),
		(*ObsoleteWeakUpdateCommand_DropOnlineSubscriptions)(nil),
		(*ObsoleteWeakUpdateCommand_MyTyping)(nil),
		(*ObsoleteWeakUpdateCommand_SubscribeToTypings)(nil),
		(*ObsoleteWeakUpdateCommand_UnsubscribeFromTypings)(nil),
		(*ObsoleteWeakUpdateCommand_DropTypingSubscriptions)(nil),
		(*ObsoleteWeakUpdateCommand_SubscribeToEventBusUpdates)(nil),
		(*ObsoleteWeakUpdateCommand_MyOnline)(nil),
	}
}

type ObsoleteWeakUpdateCommand_ObsoleteMyTyping struct {
	Peer                 *ObsoletePeer      `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Type                 ObsoleteTypingType `protobuf:"varint,2,opt,name=type,proto3,enum=dialog.ObsoleteTypingType" json:"type,omitempty"`
	Start                bool               `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) Reset() {
	*m = ObsoleteWeakUpdateCommand_ObsoleteMyTyping{}
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateCommand_ObsoleteMyTyping) ProtoMessage() {}
func (*ObsoleteWeakUpdateCommand_ObsoleteMyTyping) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{7, 0}
}

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyTyping.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyTyping.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyTyping.Merge(m, src)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyTyping.Size(m)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyTyping.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyTyping proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) GetPeer() *ObsoletePeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) GetType() ObsoleteTypingType {
	if m != nil {
		return m.Type
	}
	return ObsoleteTypingType_OBSOLETE_TYPINGTYPE_UNKNOWN
}

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyTyping) GetStart() bool {
	if m != nil {
		return m.Start
	}
	return false
}

type ObsoleteWeakUpdateCommand_ObsoleteMyOnline struct {
	Online               bool     `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) Reset() {
	*m = ObsoleteWeakUpdateCommand_ObsoleteMyOnline{}
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) String() string {
	return proto.CompactTextString(m)
}
func (*ObsoleteWeakUpdateCommand_ObsoleteMyOnline) ProtoMessage() {}
func (*ObsoleteWeakUpdateCommand_ObsoleteMyOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_067c16ca0e27c127, []int{7, 1}
}

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyOnline.Unmarshal(m, b)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyOnline.Marshal(b, m, deterministic)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyOnline.Merge(m, src)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) XXX_Size() int {
	return xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyOnline.Size(m)
}
func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyOnline.DiscardUnknown(m)
}

var xxx_messageInfo_ObsoleteWeakUpdateCommand_ObsoleteMyOnline proto.InternalMessageInfo

func (m *ObsoleteWeakUpdateCommand_ObsoleteMyOnline) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func init() {
	proto.RegisterEnum("dialog.ObsoleteTypingType", ObsoleteTypingType_name, ObsoleteTypingType_value)
	proto.RegisterEnum("dialog.ObsoletePeer_ObsoletePeerType", ObsoletePeer_ObsoletePeerType_name, ObsoletePeer_ObsoletePeerType_value)
	proto.RegisterEnum("dialog.ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason", ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason_name, ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed_ObsoleteDisposalReason_value)
	proto.RegisterType((*ObsoletePeer)(nil), "dialog.ObsoletePeer")
	proto.RegisterType((*ObsoleteOutPeer)(nil), "dialog.ObsoleteOutPeer")
	proto.RegisterType((*ObsoletePeersList)(nil), "dialog.ObsoletePeersList")
	proto.RegisterType((*ObsoleteGetDifferenceCommand)(nil), "dialog.ObsoleteGetDifferenceCommand")
	proto.RegisterType((*ObsoleteSeqUpdateBox)(nil), "dialog.ObsoleteSeqUpdateBox")
	proto.RegisterType((*ObsoleteWeakUpdateBox)(nil), "dialog.ObsoleteWeakUpdateBox")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateTyping)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateTyping")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateUserLastSeen)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateUserLastSeen")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateGroupOnline)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateGroupOnline")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusMessage)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateEventBusMessage")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceConnected)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateEventBusDeviceConnected")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDeviceDisconnected)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateEventBusDeviceDisconnected")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateEventBusDisposed)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateEventBusDisposed")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateIncomingCall)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateIncomingCall")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateCallHandled)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateCallHandled")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateCallDisposed)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateCallDisposed")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateForceReloadState")
	proto.RegisterType((*ObsoleteWeakUpdateBox_ObsoleteUpdateForceReloadState_ObsoleteForceReloadField)(nil), "dialog.ObsoleteWeakUpdateBox.ObsoleteUpdateForceReloadState.ObsoleteForceReloadField")
	proto.RegisterType((*ObsoleteServiceUpdate)(nil), "dialog.ObsoleteServiceUpdate")
	proto.RegisterType((*ObsoleteWeakUpdateCommand)(nil), "dialog.ObsoleteWeakUpdateCommand")
	proto.RegisterType((*ObsoleteWeakUpdateCommand_ObsoleteMyTyping)(nil), "dialog.ObsoleteWeakUpdateCommand.ObsoleteMyTyping")
	proto.RegisterType((*ObsoleteWeakUpdateCommand_ObsoleteMyOnline)(nil), "dialog.ObsoleteWeakUpdateCommand.ObsoleteMyOnline")
}

func init() { proto.RegisterFile("obsolete.proto", fileDescriptor_067c16ca0e27c127) }

var fileDescriptor_067c16ca0e27c127 = []byte{
	// 1753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x41, 0x73, 0x1b, 0x49,
	0x15, 0xd6, 0x48, 0xb6, 0x2c, 0x3f, 0x19, 0x23, 0xba, 0x12, 0x47, 0x9e, 0xd8, 0x89, 0xa3, 0x22,
	0xac, 0xcb, 0x14, 0xf2, 0xae, 0x42, 0xed, 0x42, 0xa0, 0x36, 0x58, 0xf2, 0x24, 0x12, 0xb1, 0x2d,
	0x55, 0x4b, 0xde, 0x6c, 0x6a, 0x0b, 0xcc, 0x68, 0xa6, 0x2d, 0x4f, 0xed, 0x68, 0x66, 0x76, 0x7a,
	0x14, 0xa2, 0x03, 0x1c, 0x96, 0x0b, 0x27, 0xaa, 0x80, 0xbf, 0xc0, 0x81, 0x3b, 0x27, 0x72, 0xe3,
	0x07, 0x70, 0xe2, 0xc4, 0x95, 0x82, 0x2a, 0x7e, 0x03, 0x27, 0x6a, 0xba, 0x7b, 0x46, 0xad, 0x91,
	0x46, 0xb6, 0x4c, 0xb1, 0x27, 0xe9, 0x75, 0xbf, 0xf7, 0xbd, 0xaf, 0x5f, 0x77, 0xbf, 0xd7, 0x6f,
	0x60, 0xd3, 0xed, 0x53, 0xd7, 0x26, 0x01, 0xa9, 0x7a, 0xbe, 0x1b, 0xb8, 0x28, 0x6f, 0x5a, 0xba,
	0xed, 0x0e, 0xd4, 0xbb, 0xd4, 0xd0, 0x6d, 0xdd, 0xeb, 0x1f, 0x8a, 0x5f, 0x3e, 0xad, 0x3e, 0x18,
	0xb8, 0xee, 0xc0, 0x26, 0x87, 0x4c, 0xea, 0x8f, 0x2e, 0x0f, 0x7f, 0xee, 0xeb, 0x9e, 0x47, 0x7c,
	0x2a, 0xe6, 0xef, 0x27, 0xe7, 0xc9, 0xd0, 0x0b, 0xc6, 0x62, 0x72, 0x47, 0x4c, 0xea, 0x9e, 0x75,
	0xa8, 0x3b, 0x8e, 0x1b, 0xe8, 0x81, 0xe5, 0x3a, 0xc2, 0xb4, 0xf2, 0xe7, 0x2c, 0x6c, 0xb4, 0x05,
	0x99, 0x0e, 0x21, 0x3e, 0xfa, 0x3e, 0xac, 0x04, 0x63, 0x8f, 0x94, 0x95, 0x3d, 0x65, 0x7f, 0xb3,
	0xf6, 0xb8, 0xca, 0x99, 0x55, 0x65, 0x9d, 0x29, 0xa1, 0x37, 0xf6, 0x08, 0x66, 0x26, 0x68, 0x13,
	0xb2, 0x96, 0x59, 0xce, 0xee, 0x29, 0xfb, 0xab, 0x38, 0x6b, 0x99, 0xa8, 0x06, 0xab, 0x34, 0xf0,
	0x5b, 0x66, 0x39, 0xb7, 0xa7, 0xec, 0x17, 0x6b, 0x3b, 0x55, 0xce, 0xa4, 0x1a, 0xd1, 0xac, 0x76,
	0x03, 0xdf, 0x72, 0x06, 0x9f, 0xe8, 0xf6, 0x88, 0x60, 0xae, 0x8a, 0x1e, 0x42, 0x51, 0x37, 0x0c,
	0x42, 0xe9, 0xc5, 0x95, 0x4e, 0xaf, 0xca, 0x2b, 0x7b, 0xca, 0x7e, 0x0e, 0x03, 0x1f, 0x6a, 0xea,
	0xf4, 0xaa, 0xf2, 0x6b, 0x05, 0x4a, 0x49, 0xff, 0x68, 0x17, 0xb6, 0xdb, 0xf5, 0x6e, 0xfb, 0x44,
	0xeb, 0x69, 0x17, 0x1d, 0x4d, 0xc3, 0xbd, 0xd7, 0x1d, 0xed, 0xe2, 0xfc, 0xec, 0xe5, 0x59, 0xfb,
	0xd5, 0x59, 0x29, 0x33, 0x7f, 0xba, 0x83, 0x5b, 0x9f, 0x1c, 0xf5, 0xb4, 0x92, 0x82, 0xee, 0xc3,
	0xbd, 0xd9, 0xe9, 0x17, 0xb8, 0x7d, 0xde, 0x29, 0x65, 0xd1, 0x36, 0xdc, 0x9d, 0x9d, 0xec, 0xb6,
	0x3a, 0xa5, 0x95, 0xca, 0x67, 0xf0, 0xf5, 0x88, 0x49, 0x7b, 0x14, 0xb0, 0xe8, 0xed, 0xc3, 0x8a,
	0x47, 0x88, 0xcf, 0xa2, 0x57, 0xac, 0xdd, 0x99, 0x17, 0x3d, 0xcc, 0x34, 0xd0, 0x03, 0x90, 0x56,
	0xc5, 0x82, 0x36, 0xbd, 0xce, 0x67, 0xf0, 0x0d, 0xd9, 0x8a, 0x9e, 0x58, 0x34, 0x40, 0x07, 0xb0,
	0x1a, 0x1a, 0xd3, 0xb2, 0xb2, 0x97, 0x4b, 0xc5, 0xe7, 0x2a, 0x95, 0x5f, 0x29, 0xb0, 0x13, 0x8d,
	0xbf, 0x20, 0xc1, 0xb1, 0x75, 0x79, 0x49, 0x7c, 0xe2, 0x18, 0xa4, 0xe1, 0x0e, 0x87, 0xba, 0x63,
	0xa2, 0xef, 0x40, 0x8e, 0x92, 0x2f, 0x04, 0xd5, 0xfb, 0x33, 0x9b, 0xd3, 0x72, 0x82, 0x27, 0x35,
	0xbe, 0x37, 0xa1, 0x1e, 0xba, 0x13, 0xee, 0xa6, 0x1e, 0x10, 0xc6, 0x75, 0x03, 0x73, 0x21, 0x5c,
	0x86, 0xe1, 0x3a, 0x97, 0xd6, 0x80, 0x2d, 0x23, 0xc7, 0x97, 0x31, 0x19, 0xa9, 0xfc, 0x4e, 0x81,
	0x3b, 0x11, 0x8b, 0x2e, 0xf9, 0xe2, 0xdc, 0x33, 0xf5, 0x80, 0xd4, 0xdd, 0xb7, 0xa8, 0x34, 0xf1,
	0xbe, 0xba, 0xc8, 0x81, 0x36, 0xb9, 0x2c, 0xdc, 0x58, 0x9c, 0xa6, 0x59, 0xc2, 0xf5, 0x71, 0x40,
	0x28, 0x23, 0xdc, 0xcc, 0xe0, 0x84, 0x51, 0xbd, 0x08, 0xeb, 0x23, 0xf6, 0xaf, 0xef, 0xbe, 0xad,
	0xfc, 0x49, 0x85, 0xbb, 0x11, 0xa9, 0x57, 0x44, 0xff, 0x7c, 0xc2, 0x0a, 0xc1, 0x0a, 0xf3, 0xa1,
	0xb0, 0x85, 0xb0, 0xff, 0xe8, 0x04, 0xf2, 0xc1, 0xd8, 0xb3, 0x9c, 0x01, 0x23, 0x56, 0xac, 0xd5,
	0x92, 0x51, 0x9f, 0x82, 0x88, 0x47, 0xf9, 0x48, 0x8f, 0x59, 0x36, 0x33, 0x58, 0x60, 0xa0, 0x9f,
	0xc2, 0xc6, 0x88, 0x12, 0xff, 0x44, 0xa7, 0x41, 0x97, 0x10, 0x47, 0xac, 0xe6, 0x7b, 0xcb, 0x60,
	0x9e, 0x4b, 0xf6, 0xcd, 0x0c, 0x9e, 0xc2, 0x43, 0x9f, 0x41, 0x71, 0xe0, 0xbb, 0x23, 0xaf, 0xed,
	0xd8, 0x96, 0x43, 0xd8, 0x05, 0x2a, 0xd6, 0x3e, 0x5a, 0x06, 0xfe, 0xc5, 0xc4, 0xbc, 0x99, 0xc1,
	0x32, 0x1a, 0xfa, 0x09, 0x40, 0x7f, 0x44, 0x4f, 0x09, 0xa5, 0xfa, 0x80, 0x94, 0x57, 0x19, 0xf6,
	0x0f, 0x96, 0xc1, 0xd6, 0xde, 0x10, 0x27, 0xa8, 0xc7, 0x10, 0xcd, 0x0c, 0x96, 0x00, 0xd1, 0x08,
	0x50, 0x7f, 0x44, 0x8f, 0xc9, 0x1b, 0x2b, 0x3c, 0xa5, 0x8e, 0x43, 0x8c, 0x80, 0x98, 0xe5, 0x3c,
	0x73, 0xd3, 0xb8, 0x8d, 0x9b, 0x04, 0x54, 0x33, 0x83, 0xe7, 0x38, 0x40, 0xbf, 0x84, 0xbb, 0xf1,
	0xe8, 0xb1, 0x45, 0x8d, 0xd8, 0xf3, 0x1a, 0xf3, 0xfc, 0xfc, 0xf6, 0x9e, 0x65, 0xb4, 0x66, 0x06,
	0xcf, 0x77, 0x83, 0x7e, 0x06, 0xc5, 0x70, 0xc2, 0xa2, 0x9e, 0x4b, 0x89, 0x59, 0x2e, 0x30, 0xaf,
	0x3f, 0xbc, 0x95, 0x57, 0x81, 0x11, 0xee, 0x9b, 0x04, 0x19, 0x7a, 0xb8, 0x74, 0x7d, 0x83, 0x60,
	0x62, 0xbb, 0xba, 0x59, 0x5e, 0x5f, 0xde, 0xc3, 0xf3, 0x89, 0x79, 0x37, 0xbc, 0x97, 0xa1, 0x07,
	0x09, 0x32, 0x3c, 0xd6, 0x96, 0x63, 0xb8, 0x43, 0xcb, 0x19, 0x34, 0x74, 0xdb, 0x2e, 0xc3, 0xf2,
	0xc7, 0xba, 0x25, 0xd9, 0x87, 0xc7, 0x5a, 0xc6, 0x0b, 0x8f, 0xb5, 0x11, 0x8e, 0xeb, 0x8e, 0x69,
	0x13, 0xb3, 0x5c, 0x5c, 0xfe, 0x58, 0x37, 0x26, 0xe6, 0x21, 0x79, 0x09, 0x2d, 0x24, 0x1f, 0x8a,
	0xf1, 0x0e, 0x6c, 0x2c, 0x4f, 0xbe, 0x21, 0xd9, 0x87, 0xe4, 0x65, 0x3c, 0xf5, 0x0f, 0x52, 0x12,
	0x94, 0xd3, 0xc2, 0x12, 0xe5, 0x62, 0x0b, 0xf2, 0xe1, 0x35, 0x6f, 0x45, 0xf5, 0x55, 0x48, 0xa8,
	0x2a, 0xca, 0x75, 0x8e, 0x95, 0x6b, 0x35, 0x89, 0xc0, 0xfd, 0x48, 0x35, 0x5a, 0x85, 0x82, 0x45,
	0xf9, 0x28, 0xcb, 0x0d, 0x05, 0x1c, 0xcb, 0xea, 0x3b, 0x05, 0xd4, 0xf4, 0x4c, 0x23, 0x51, 0x50,
	0xa6, 0x28, 0xec, 0x41, 0x91, 0x78, 0xae, 0x71, 0x75, 0x6a, 0xd9, 0xb6, 0x45, 0x45, 0x29, 0x93,
	0x87, 0xc2, 0x22, 0x61, 0xb2, 0x63, 0xdf, 0x8b, 0xa8, 0xae, 0x62, 0x69, 0x04, 0x7d, 0x0b, 0x36,
	0xb9, 0xd4, 0xd0, 0x03, 0x32, 0x70, 0xfd, 0x31, 0xa3, 0xb6, 0x8e, 0x13, 0xa3, 0x9c, 0xbc, 0x48,
	0x6c, 0xab, 0x11, 0x79, 0x2e, 0xab, 0x2f, 0x61, 0x3b, 0x35, 0x8d, 0xa1, 0x32, 0xac, 0xb1, 0x34,
	0x16, 0x73, 0x8f, 0xc4, 0xb0, 0xe8, 0x18, 0xee, 0xc8, 0x09, 0x44, 0x58, 0xb9, 0xa0, 0xfe, 0x55,
	0x81, 0xdd, 0x85, 0x89, 0x2b, 0xb4, 0xeb, 0x8f, 0xa8, 0xc0, 0x5b, 0xc7, 0x5c, 0x40, 0x1f, 0x41,
	0x81, 0x12, 0xc7, 0x8c, 0xf7, 0xe9, 0x9a, 0xba, 0x1a, 0x2b, 0xa3, 0x06, 0x6c, 0xf2, 0xff, 0x3c,
	0x3d, 0xc4, 0x6f, 0xa6, 0xb9, 0xe6, 0x1f, 0x7e, 0x97, 0x9b, 0x27, 0x4c, 0xc2, 0x55, 0x0e, 0x45,
	0x6a, 0x5e, 0x61, 0x25, 0x34, 0x12, 0xd5, 0xdf, 0x28, 0xf0, 0xf8, 0x46, 0x19, 0x32, 0x65, 0x5d,
	0x4f, 0xa6, 0x4e, 0xdf, 0x35, 0xab, 0x8a, 0xce, 0x85, 0x0a, 0x05, 0x53, 0x5e, 0x4d, 0x0e, 0xc7,
	0xb2, 0xfa, 0x5b, 0x05, 0xf6, 0x6f, 0x9a, 0x38, 0xbf, 0x2a, 0x4e, 0x1f, 0xc2, 0x83, 0xc5, 0x59,
	0x75, 0x3e, 0x11, 0xf5, 0x8f, 0xd9, 0xe4, 0xb5, 0x91, 0x33, 0x59, 0x78, 0x6d, 0xc2, 0x64, 0x20,
	0xac, 0x72, 0x58, 0x48, 0x13, 0xb0, 0xac, 0xbc, 0xaa, 0x28, 0x23, 0xe4, 0xae, 0xcd, 0x08, 0x1f,
	0x43, 0xd1, 0xb4, 0xa8, 0x67, 0xeb, 0xe3, 0x33, 0x7d, 0x18, 0x15, 0xfa, 0xc5, 0x6f, 0x6c, 0xd9,
	0x00, 0x3d, 0x83, 0x0d, 0x3d, 0x08, 0xc2, 0x4e, 0xa1, 0xe5, 0x98, 0xe4, 0xad, 0xa8, 0xe6, 0x0b,
	0xa3, 0x38, 0x65, 0x80, 0x3e, 0x80, 0x35, 0x97, 0x3f, 0x7b, 0x45, 0x89, 0xbe, 0x97, 0x64, 0x2b,
	0x5e, 0xc5, 0x38, 0xd2, 0x53, 0x83, 0xe4, 0x25, 0x95, 0x92, 0x72, 0x6a, 0xa0, 0x92, 0x44, 0xb3,
	0x4b, 0x12, 0x55, 0xdf, 0xe5, 0x92, 0x1b, 0x24, 0x67, 0xeb, 0xff, 0x9b, 0x5f, 0x34, 0x80, 0xbc,
	0x4f, 0x74, 0xea, 0x3a, 0x22, 0x3b, 0xb7, 0x6f, 0x5b, 0x50, 0xe2, 0x29, 0x3e, 0xa0, 0xdb, 0x98,
	0xc1, 0x62, 0x01, 0x5f, 0xf9, 0xbb, 0x02, 0x5b, 0xf3, 0x55, 0xd0, 0x37, 0x61, 0x2f, 0x6e, 0x5f,
	0x8e, 0x5b, 0xdd, 0x4e, 0xbb, 0x7b, 0x74, 0x72, 0x81, 0xb5, 0xa3, 0x6e, 0xfb, 0x4c, 0x6a, 0x90,
	0x1e, 0xc3, 0xa3, 0x54, 0x2d, 0xac, 0xfd, 0x58, 0x6b, 0xf4, 0xb4, 0xe3, 0x92, 0x82, 0x1e, 0xc1,
	0x6e, 0xaa, 0x5a, 0xfd, 0xbc, 0xfb, 0xba, 0x94, 0x45, 0x15, 0x78, 0x90, 0xaa, 0xa2, 0x9d, 0x1d,
	0x6b, 0xc7, 0xa5, 0x1c, 0xfa, 0x36, 0xbc, 0x97, 0xaa, 0x73, 0x74, 0xd6, 0x7d, 0xa5, 0xe1, 0x8b,
	0x5e, 0xeb, 0x54, 0x6b, 0x9f, 0xf7, 0x4a, 0x2b, 0xea, 0x7f, 0xb2, 0xc9, 0x6b, 0x99, 0x7c, 0x8a,
	0xa0, 0x21, 0xe4, 0x2f, 0x2d, 0x62, 0x9b, 0x51, 0x5b, 0x74, 0xfe, 0xbf, 0x3c, 0x6c, 0xe2, 0x69,
	0x69, 0xe2, 0x79, 0x88, 0x8e, 0x85, 0x13, 0xf5, 0xdf, 0x0a, 0x94, 0xd3, 0x94, 0xd0, 0xc7, 0xf0,
	0x35, 0x9f, 0x89, 0xc7, 0x8c, 0x02, 0x15, 0xa5, 0x7d, 0x6b, 0xe6, 0xd4, 0x68, 0x61, 0x8b, 0xde,
	0xcc, 0xe0, 0x69, 0x75, 0xf4, 0x23, 0xd8, 0xe4, 0x03, 0x0d, 0xd7, 0x09, 0x74, 0x23, 0xa0, 0xe2,
	0xd8, 0xa5, 0x03, 0x24, 0xf4, 0xd1, 0x51, 0xc4, 0xa0, 0x69, 0xd1, 0x20, 0xac, 0xa5, 0x3c, 0x95,
	0x6c, 0xcf, 0x4b, 0x25, 0xac, 0xab, 0x9c, 0x90, 0x10, 0x16, 0xf5, 0x35, 0x58, 0x65, 0x6b, 0x9d,
	0xee, 0x9a, 0xae, 0x26, 0x4d, 0x53, 0x97, 0xf8, 0x61, 0xd2, 0xe4, 0x11, 0x9c, 0xd3, 0xa2, 0x29,
	0xb7, 0x69, 0xd1, 0x0a, 0x90, 0xe7, 0xce, 0x2a, 0x7f, 0x59, 0x9b, 0xe4, 0x89, 0xc9, 0xde, 0x45,
	0x7d, 0xeb, 0x4b, 0x40, 0x74, 0xd4, 0xa7, 0x86, 0x6f, 0xf5, 0x49, 0xcf, 0xe5, 0x15, 0x3e, 0x8a,
	0xf3, 0xc2, 0x55, 0xce, 0x31, 0x43, 0x5d, 0xd8, 0x1a, 0x39, 0xf1, 0xf8, 0x73, 0xdf, 0x1d, 0x46,
	0x80, 0xd9, 0xeb, 0x01, 0x53, 0x4c, 0x11, 0x86, 0x7b, 0xa6, 0xef, 0x8a, 0xc7, 0x47, 0x97, 0x6b,
	0x78, 0xec, 0xab, 0x8b, 0xd8, 0x8c, 0xf4, 0xdd, 0x4c, 0x33, 0x44, 0x1d, 0x28, 0x0c, 0xc7, 0xe2,
	0xe1, 0xb6, 0x76, 0x5d, 0x1f, 0x2a, 0x42, 0x15, 0xcf, 0x9c, 0x8e, 0xe3, 0x3e, 0x34, 0x46, 0x49,
	0xc4, 0x91, 0x0f, 0x52, 0xd1, 0x7d, 0xdc, 0x38, 0x8e, 0xc2, 0x6c, 0x4e, 0x1c, 0x23, 0xc0, 0xf5,
	0xe5, 0xe3, 0x18, 0x81, 0x8a, 0x38, 0x72, 0x71, 0x3a, 0x8e, 0x70, 0x93, 0x38, 0xce, 0x31, 0x44,
	0x9f, 0x82, 0x2a, 0xd1, 0x8f, 0x4a, 0x3c, 0x0f, 0x1b, 0x15, 0x7d, 0x45, 0x3a, 0xec, 0x02, 0x5b,
	0xbe, 0x43, 0xe2, 0x75, 0xba, 0xb1, 0xfc, 0x0e, 0xc5, 0x1d, 0x77, 0x8c, 0xa2, 0x7e, 0x29, 0x7d,
	0xeb, 0x8a, 0xb6, 0x70, 0x89, 0x9e, 0x21, 0xea, 0x0d, 0xb2, 0x37, 0xec, 0x0d, 0xf8, 0x07, 0x18,
	0x3f, 0x60, 0x87, 0xb4, 0x80, 0xb9, 0xa0, 0x1e, 0xc8, 0x1c, 0xc4, 0x7b, 0x7a, 0x0b, 0xf2, 0x2e,
	0x5f, 0xa8, 0xc2, 0x54, 0x85, 0x54, 0x5f, 0x87, 0x35, 0x83, 0x2f, 0xec, 0xa0, 0x0b, 0x68, 0xd6,
	0x11, 0x7a, 0x08, 0xf7, 0xe3, 0xd4, 0xdf, 0x7b, 0xdd, 0x69, 0x9d, 0xbd, 0x48, 0x7c, 0xaa, 0xdb,
	0x81, 0xf2, 0x3c, 0x85, 0x9e, 0xf6, 0x69, 0xaf, 0xa4, 0xd4, 0xfe, 0x95, 0x85, 0x42, 0x84, 0x8a,
	0x3e, 0x97, 0xfe, 0x2f, 0x4a, 0x35, 0xea, 0xa2, 0xc9, 0xca, 0xe3, 0x2f, 0xff, 0xf6, 0xcf, 0xdf,
	0x67, 0x1f, 0x56, 0xd4, 0xc3, 0x37, 0x1f, 0x1c, 0x0e, 0x7c, 0xcf, 0x38, 0x8c, 0x40, 0xe3, 0x3f,
	0x4f, 0x95, 0x03, 0x34, 0x04, 0x88, 0x3f, 0x5f, 0x51, 0x94, 0x72, 0x40, 0xd4, 0x9d, 0x64, 0x8c,
	0xe5, 0x4f, 0x5e, 0x95, 0xf7, 0x98, 0xab, 0x47, 0x95, 0x9d, 0x59, 0x57, 0x13, 0xec, 0xa7, 0xca,
	0xc1, 0xfb, 0x0a, 0xfa, 0x05, 0x14, 0x27, 0x67, 0x85, 0xa2, 0x47, 0xd7, 0x1e, 0x24, 0x75, 0x77,
	0x61, 0xd1, 0xab, 0xec, 0x33, 0xdf, 0x95, 0xca, 0xee, 0xac, 0x6f, 0xc9, 0xd1, 0x53, 0xe5, 0x60,
	0x5f, 0x79, 0x5f, 0xa9, 0x6f, 0xff, 0xe3, 0xd9, 0x16, 0xdc, 0xb1, 0x86, 0x55, 0xd3, 0x1e, 0x54,
	0x43, 0xed, 0x2a, 0xe5, 0x19, 0x9f, 0xf6, 0xf3, 0x6c, 0xc9, 0x4f, 0xfe, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x13, 0xba, 0x19, 0x41, 0xc3, 0x16, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObsoleteClient is the client API for Obsolete service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObsoleteClient interface {
	Obsolete(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.BytesValue, error)
	SeqUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Obsolete_SeqUpdatesClient, error)
	WeakUpdates(ctx context.Context, opts ...grpc.CallOption) (Obsolete_WeakUpdatesClient, error)
}

type obsoleteClient struct {
	cc *grpc.ClientConn
}

func NewObsoleteClient(cc *grpc.ClientConn) ObsoleteClient {
	return &obsoleteClient{cc}
}

func (c *obsoleteClient) Obsolete(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.BytesValue, error) {
	out := new(wrappers.BytesValue)
	err := c.cc.Invoke(ctx, "/dialog.Obsolete/Obsolete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obsoleteClient) SeqUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Obsolete_SeqUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Obsolete_serviceDesc.Streams[0], "/dialog.Obsolete/SeqUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &obsoleteSeqUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Obsolete_SeqUpdatesClient interface {
	Recv() (*ObsoleteSeqUpdateBox, error)
	grpc.ClientStream
}

type obsoleteSeqUpdatesClient struct {
	grpc.ClientStream
}

func (x *obsoleteSeqUpdatesClient) Recv() (*ObsoleteSeqUpdateBox, error) {
	m := new(ObsoleteSeqUpdateBox)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *obsoleteClient) WeakUpdates(ctx context.Context, opts ...grpc.CallOption) (Obsolete_WeakUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Obsolete_serviceDesc.Streams[1], "/dialog.Obsolete/WeakUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &obsoleteWeakUpdatesClient{stream}
	return x, nil
}

type Obsolete_WeakUpdatesClient interface {
	Send(*ObsoleteWeakUpdateCommand) error
	Recv() (*ObsoleteWeakUpdateBox, error)
	grpc.ClientStream
}

type obsoleteWeakUpdatesClient struct {
	grpc.ClientStream
}

func (x *obsoleteWeakUpdatesClient) Send(m *ObsoleteWeakUpdateCommand) error {
	return x.ClientStream.SendMsg(m)
}

func (x *obsoleteWeakUpdatesClient) Recv() (*ObsoleteWeakUpdateBox, error) {
	m := new(ObsoleteWeakUpdateBox)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ObsoleteServer is the server API for Obsolete service.
type ObsoleteServer interface {
	Obsolete(context.Context, *wrappers.BytesValue) (*wrappers.BytesValue, error)
	SeqUpdates(*empty.Empty, Obsolete_SeqUpdatesServer) error
	WeakUpdates(Obsolete_WeakUpdatesServer) error
}

// UnimplementedObsoleteServer can be embedded to have forward compatible implementations.
type UnimplementedObsoleteServer struct {
}

func (*UnimplementedObsoleteServer) Obsolete(ctx context.Context, req *wrappers.BytesValue) (*wrappers.BytesValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Obsolete not implemented")
}
func (*UnimplementedObsoleteServer) SeqUpdates(req *empty.Empty, srv Obsolete_SeqUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SeqUpdates not implemented")
}
func (*UnimplementedObsoleteServer) WeakUpdates(srv Obsolete_WeakUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method WeakUpdates not implemented")
}

func RegisterObsoleteServer(s *grpc.Server, srv ObsoleteServer) {
	s.RegisterService(&_Obsolete_serviceDesc, srv)
}

func _Obsolete_Obsolete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.BytesValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObsoleteServer).Obsolete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Obsolete/Obsolete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObsoleteServer).Obsolete(ctx, req.(*wrappers.BytesValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obsolete_SeqUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObsoleteServer).SeqUpdates(m, &obsoleteSeqUpdatesServer{stream})
}

type Obsolete_SeqUpdatesServer interface {
	Send(*ObsoleteSeqUpdateBox) error
	grpc.ServerStream
}

type obsoleteSeqUpdatesServer struct {
	grpc.ServerStream
}

func (x *obsoleteSeqUpdatesServer) Send(m *ObsoleteSeqUpdateBox) error {
	return x.ServerStream.SendMsg(m)
}

func _Obsolete_WeakUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObsoleteServer).WeakUpdates(&obsoleteWeakUpdatesServer{stream})
}

type Obsolete_WeakUpdatesServer interface {
	Send(*ObsoleteWeakUpdateBox) error
	Recv() (*ObsoleteWeakUpdateCommand, error)
	grpc.ServerStream
}

type obsoleteWeakUpdatesServer struct {
	grpc.ServerStream
}

func (x *obsoleteWeakUpdatesServer) Send(m *ObsoleteWeakUpdateBox) error {
	return x.ServerStream.SendMsg(m)
}

func (x *obsoleteWeakUpdatesServer) Recv() (*ObsoleteWeakUpdateCommand, error) {
	m := new(ObsoleteWeakUpdateCommand)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Obsolete_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dialog.Obsolete",
	HandlerType: (*ObsoleteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Obsolete",
			Handler:    _Obsolete_Obsolete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SeqUpdates",
			Handler:       _Obsolete_SeqUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WeakUpdates",
			Handler:       _Obsolete_WeakUpdates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "obsolete.proto",
}
